interface objDefine {
  [key: string]: string;
}

export const deviconClasses: objDefine = {
  // JavaScript variations
  javascript: 'devicon-javascript-plain',
  js: 'devicon-javascript-plain',
  es6: 'devicon-javascript-plain',
  es2015: 'devicon-javascript-plain',

  // TypeScript variations
  typescript: 'devicon-typescript-plain',
  ts: 'devicon-typescript-plain',

  // React variations
  react: 'devicon-react-original',
  reactjs: 'devicon-react-original',
  'react native': 'devicon-react-original',

  // Next.js variations
  nextjs: 'devicon-nextjs-plain',
  next: 'devicon-nextjs-plain',

  // Node.js variations
  nodejs: 'devicon-nodejs-plain',
  node: 'devicon-nodejs-plain',
  express: 'devicon-express-original',

  // Bun.js variations
  bun: 'devicon-bun-plain',
  bunjs: 'devicon-bun-plain',

  // Deno.js variations
  deno: 'devicon-denojs-original',
  denojs: 'devicon-denojs-plain',

  // Python variations
  python: 'devicon-python-plain',
  py: 'devicon-python-plain',
  django: 'devicon-django-plain',
  flask: 'devicon-flask-original',
  fastapi: 'devicon-fastapi-plain',

  // Java variations
  java: 'devicon-java-plain',
  spring: 'devicon-spring-plain',
  springboot: 'devicon-spring-plain',

  // C++ variations
  'c++': 'devicon-cplusplus-plain',
  cpp: 'devicon-cplusplus-plain',

  // C# variations
  'c#': 'devicon-csharp-plain',
  csharp: 'devicon-csharp-plain',
  dotnet: 'devicon-dotnetcore-plain',

  // PHP variations
  php: 'devicon-php-plain',
  laravel: 'devicon-laravel-plain',
  symfony: 'devicon-symfony-original',

  // HTML variations
  html: 'devicon-html5-plain',
  html5: 'devicon-html5-plain',

  // CSS variations
  css: 'devicon-css3-plain',
  css3: 'devicon-css3-plain',
  sass: 'devicon-sass-plain',
  scss: 'devicon-sass-plain',
  less: 'devicon-less-plain',
  stylus: 'devicon-stylus-plain',

  // Git variations
  git: 'devicon-git-plain',
  github: 'devicon-github-original',
  gitlab: 'devicon-gitlab-plain',
  bitbucket: 'devicon-bitbucket-plain',

  // Docker variations
  docker: 'devicon-docker-plain',
  kubernetes: 'devicon-kubernetes-plain',
  k8s: 'devicon-kubernetes-plain',

  // Database variations
  mongodb: 'devicon-mongodb-plain',
  mongo: 'devicon-mongodb-plain',
  mysql: 'devicon-mysql-plain',
  postgresql: 'devicon-postgresql-plain',
  postgres: 'devicon-postgresql-plain',
  redis: 'devicon-redis-plain',
  sqlite: 'devicon-sqlite-plain',
  oracle: 'devicon-oracle-plain',
  cassandra: 'devicon-cassandra-plain',
  couchdb: 'devicon-couchdb-plain',

  // Cloud variations
  aws: 'devicon-amazonwebservices-original',
  'amazon web services': 'devicon-amazonwebservices-original',
  azure: 'devicon-azure-plain',
  'azure devops': 'devicon-azure-plain',
  gcp: 'devicon-googlecloud-plain',
  'google cloud': 'devicon-googlecloud-plain',
  digitalocean: 'devicon-digitalocean-plain',
  heroku: 'devicon-heroku-plain',
  firebase: 'devicon-firebase-plain',

  // Frontend Framework variations
  vue: 'devicon-vuejs-plain',
  vuejs: 'devicon-vuejs-plain',
  angular: 'devicon-angularjs-plain',
  angularjs: 'devicon-angularjs-plain',
  svelte: 'devicon-svelte-plain',
  ember: 'devicon-ember-original',
  backbone: 'devicon-backbone-plain',
  reactnative: 'devicon-react-original',

  // CSS Framework variations
  tailwind: 'devicon-tailwindcss-plain',
  tailwindcss: 'devicon-tailwindcss-plain',
  bootstrap: 'devicon-bootstrap-plain',
  bulma: 'devicon-bulma-plain',
  materialui: 'devicon-materialui-plain',
  'material ui': 'devicon-materialui-plain',

  // Testing variations
  jest: 'devicon-jest-plain',
  mocha: 'devicon-mocha-plain',
  jasmine: 'devicon-jasmine-plain',
  karma: 'devicon-karma-plain',
  selenium: 'devicon-selenium-original',
  cypress: 'devicon-cypress-plain',
  playwright: 'devicon-playwright-plain',
  puppeteer: 'devicon-puppeteer-plain',
  nightwatch: 'devicon-nightwatch-plain',
  ava: 'devicon-ava-plain',

  // Build Tools variations
  webpack: 'devicon-webpack-plain',
  babel: 'devicon-babel-plain',
  gulp: 'devicon-gulp-plain',
  grunt: 'devicon-grunt-plain',
  parcel: 'devicon-parcel-plain',
  rollup: 'devicon-rollup-plain',
  rollupjs: 'devicon-rollup-plain',

  // Package Manager variations
  npm: 'devicon-npm-original-wordmark',
  yarn: 'devicon-yarn-plain',
  pnpm: 'devicon-npm-original-wordmark',

  // IDE variations
  vscode: 'devicon-vscode-plain',
  intellij: 'devicon-intellij-plain',
  webstorm: 'devicon-webstorm-plain',
  pycharm: 'devicon-pycharm-plain',
  phpstorm: 'devicon-phpstorm-plain',
  atom: 'devicon-atom-original',
  sublime: 'devicon-sublime-plain',
  cursor: 'devicon-cursor-plain',

  // Version Control variations
  svn: 'devicon-svn-plain',
  mercurial: 'devicon-mercurial-plain',

  // Server variations
  nginx: 'devicon-nginx-plain',
  apache: 'devicon-apache-plain',
  tomcat: 'devicon-tomcat-plain',

  // Mobile variations
  android: 'devicon-android-plain',
  ios: 'devicon-apple-original',
  flutter: 'devicon-flutter-plain',
  dart: 'devicon-dart-plain',
  kotlin: 'devicon-kotlin-plain',
  swift: 'devicon-swift-plain',

  // Game Development variations
  unity: 'devicon-unity-original',
  unreal: 'devicon-unrealengine-original',
  blender: 'devicon-blender-plain',
  godot: 'devicon-godot-plain',
  godotengine: 'devicon-godot-plain',

  // Design & UI/UX Tools
  figma: 'devicon-figma-plain',
  sketch: 'devicon-sketch-line',
  adobexd: 'devicon-xd-plain',
  photoshop: 'devicon-photoshop-plain',
  illustrator: 'devicon-illustrator-plain',
  indesign: 'devicon-indesign-plain',
  aftereffects: 'devicon-aftereffects-plain',
  premiere: 'devicon-premiere-plain',
  canva: 'devicon-canva-plain',
  zeplin: 'devicon-zeplin-plain',
  invision: 'devicon-invision-plain',
  framer: 'devicon-framer-plain',
  protopie: 'devicon-protopie-plain',
  principle: 'devicon-principle-plain',
  'adobe creative cloud': 'devicon-adobe-plain',
  'adobe cc': 'devicon-adobe-plain',
  'adobe photoshop': 'devicon-photoshop-plain',
  'adobe illustrator': 'devicon-illustrator-plain',
  'adobe after effects': 'devicon-aftereffects-plain',
  'adobe premiere': 'devicon-premiere-plain',
  'adobe animate': 'devicon-animate-plain',
  'adobe audition': 'devicon-audition-plain',

  // Project Management variations
  jira: 'devicon-jira-plain',
  trello: 'devicon-trello-plain',
  confluence: 'devicon-confluence-original',
  slack: 'devicon-slack-plain',

  // Other Languages variations
  go: 'devicon-go-plain',
  golang: 'devicon-go-plain',
  rust: 'devicon-rust-plain',
  ruby: 'devicon-ruby-plain',
  rails: 'devicon-rails-plain',
  scala: 'devicon-scala-plain',
  haskell: 'devicon-haskell-plain',
  erlang: 'devicon-erlang-plain',
  elixir: 'devicon-elixir-plain',
  perl: 'devicon-perl-plain',
  r: 'devicon-r-plain',
  matlab: 'devicon-matlab-plain',

  // Other Tools variations
  graphql: 'devicon-graphql-plain',
  socketio: 'devicon-socketio-original',
  threejs: 'devicon-threejs-original',
  webgl: 'devicon-webgl-plain',
  electron: 'devicon-electron-original',
  gatsby: 'devicon-gatsby-plain',
  nuxt: 'devicon-nuxtjs-plain',
  meteor: 'devicon-meteor-plain',
  markdown: 'devicon-markdown-original',
  bash: 'devicon-bash-plain',
  ssh: 'devicon-ssh-original',
  vim: 'devicon-vim-plain',
  linux: 'devicon-linux-plain',
  ubuntu: 'devicon-ubuntu-plain',
  debian: 'devicon-debian-plain',
  windows: 'devicon-windows8-original',
  apple: 'devicon-apple-original',

  // Marketing & Social Media
  facebook: 'devicon-facebook-plain',
  instagram: 'devicon-instagram-plain',
  twitter: 'devicon-twitter-plain',
  linkedin: 'devicon-linkedin-plain',
  youtube: 'devicon-youtube-plain',
  tiktok: 'devicon-tiktok-plain',
  pinterest: 'devicon-pinterest-plain',
  snapchat: 'devicon-snapchat-plain',
  whatsapp: 'devicon-whatsapp-plain',
  telegram: 'devicon-telegram-plain',
  discord: 'devicon-discord-plain',
  'google analytics': 'devicon-googleanalytics-plain',
  'google ads': 'devicon-googleads-plain',
  'facebook ads': 'devicon-facebookads-plain',
  hubspot: 'devicon-hubspot-plain',
  mailchimp: 'devicon-mailchimp-plain',
  'constant contact': 'devicon-constantcontact-plain',
  hootsuite: 'devicon-hootsuite-plain',
  buffer: 'devicon-buffer-plain',
  'social media': 'devicon-socialmedia-plain',

  // Business & Productivity
  microsoft: 'devicon-microsoft-plain',
  office: 'devicon-office-plain',
  word: 'devicon-word-plain',
  excel: 'devicon-excel-plain',
  powerpoint: 'devicon-powerpoint-plain',
  outlook: 'devicon-outlook-plain',
  teams: 'devicon-teams-plain',
  sharepoint: 'devicon-sharepoint-plain',
  onedrive: 'devicon-onedrive-plain',
  zoom: 'devicon-zoom-plain',
  'google workspace': 'devicon-googleworkspace-plain',
  gmail: 'devicon-gmail-plain',
  drive: 'devicon-drive-plain',
  docs: 'devicon-docs-plain',
  sheets: 'devicon-sheets-plain',
  slides: 'devicon-slides-plain',
  calendar: 'devicon-calendar-plain',
  meet: 'devicon-meet-plain',
  asana: 'devicon-asana-plain',
  notion: 'devicon-notion-plain',
  evernote: 'devicon-evernote-plain',
  dropbox: 'devicon-dropbox-plain',
  box: 'devicon-box-plain',

  // Education & Learning
  coursera: 'devicon-coursera-plain',
  udemy: 'devicon-udemy-plain',
  'linkedin learning': 'devicon-linkedinlearning-plain',
  skillshare: 'devicon-skillshare-plain',
  khanacademy: 'devicon-khanacademy-plain',
  duolingo: 'devicon-duolingo-plain',
  'google classroom': 'devicon-googleclassroom-plain',
  moodle: 'devicon-moodle-plain',
  blackboard: 'devicon-blackboard-plain',
  canvas: 'devicon-canvas-plain',
  edx: 'devicon-edx-plain',
  'code academy': 'devicon-codeacademy-plain',
  'free code camp': 'devicon-freecodecamp-plain',
  'khan academy': 'devicon-khanacademy-plain',
  udacity: 'devicon-udacity-plain',

  // Health & Fitness
  fitbit: 'devicon-fitbit-plain',
  'apple health': 'devicon-applehealth-plain',
  'google fit': 'devicon-googlefit-plain',
  myfitnesspal: 'devicon-myfitnesspal-plain',
  strava: 'devicon-strava-plain',
  'nike run club': 'devicon-nikerunclub-plain',
  headspace: 'devicon-headspace-plain',
  calm: 'devicon-calm-plain',
  betterhelp: 'devicon-betterhelp-plain',
  teladoc: 'devicon-teladoc-plain',
  zocdoc: 'devicon-zocdoc-plain',
  goodrx: 'devicon-goodrx-plain',
  pillpack: 'devicon-pillpack-plain',
  '23andme': 'devicon-23andme-plain',
  ancestry: 'devicon-ancestry-plain',

  // Finance & Banking
  paypal: 'devicon-paypal-plain',
  stripe: 'devicon-stripe-plain',
  square: 'devicon-square-plain',
  venmo: 'devicon-venmo-plain',
  'cash app': 'devicon-cashapp-plain',
  'apple pay': 'devicon-applepay-plain',
  'google pay': 'devicon-googlepay-plain',
  'samsung pay': 'devicon-samsungpay-plain',
  chase: 'devicon-chase-plain',
  'bank of america': 'devicon-bankofamerica-plain',
  'wells fargo': 'devicon-wellsfargo-plain',
  citibank: 'devicon-citibank-plain',
  'american express': 'devicon-amex-plain',
  visa: 'devicon-visa-plain',
  mastercard: 'devicon-mastercard-plain',
  discover: 'devicon-discover-plain',
  coinbase: 'devicon-coinbase-plain',
  binance: 'devicon-binance-plain',
  robinhood: 'devicon-robinhood-plain',
  etrade: 'devicon-etrade-plain',
  fidelity: 'devicon-fidelity-plain',
  mint: 'devicon-mint-plain',
  quickbooks: 'devicon-quickbooks-plain',
  'turbo tax': 'devicon-turbotax-plain',

  // Entertainment & Media
  netflix: 'devicon-netflix-plain',
  hulu: 'devicon-hulu-plain',
  'disney plus': 'devicon-disneyplus-plain',
  'hbo max': 'devicon-hbomax-plain',
  'amazon prime': 'devicon-amazonprime-plain',
  'apple tv': 'devicon-appletv-plain',
  spotify: 'devicon-spotify-plain',
  'apple music': 'devicon-applemusic-plain',
  soundcloud: 'devicon-soundcloud-plain',
  tidal: 'devicon-tidal-plain',
  pandora: 'devicon-pandora-plain',
  iheartradio: 'devicon-iheartradio-plain',
  audible: 'devicon-audible-plain',
  kindle: 'devicon-kindle-plain',
  goodreads: 'devicon-goodreads-plain',
  medium: 'devicon-medium-plain',
  substack: 'devicon-substack-plain',
  patreon: 'devicon-patreon-plain',
  twitch: 'devicon-twitch-plain',
  mixer: 'devicon-mixer-plain',
  steam: 'devicon-steam-plain',
  'epic games': 'devicon-epicgames-plain',
  xbox: 'devicon-xbox-plain',
  playstation: 'devicon-playstation-plain',
  nintendo: 'devicon-nintendo-plain',

  // Science & Research
  'google scholar': 'devicon-googlescholar-plain',
  researchgate: 'devicon-researchgate-plain',
  academia: 'devicon-academia-plain',
  mendeley: 'devicon-mendeley-plain',
  zotero: 'devicon-zotero-plain',
  endnote: 'devicon-endnote-plain',
  scopus: 'devicon-scopus-plain',
  'web of science': 'devicon-webofscience-plain',
  pubmed: 'devicon-pubmed-plain',
  ieee: 'devicon-ieee-plain',
  springer: 'devicon-springer-plain',
  wiley: 'devicon-wiley-plain',
  elsevier: 'devicon-elsevier-plain',
  nature: 'devicon-nature-plain',
  science: 'devicon-science-plain',
  cell: 'devicon-cell-plain',
  plos: 'devicon-plos-plain',
  arxiv: 'devicon-arxiv-plain',
  biorxiv: 'devicon-biorxiv-plain',
  medrxiv: 'devicon-medrxiv-plain',
  chemrxiv: 'devicon-chemrxiv-plain',
  scihub: 'devicon-scihub-plain',
  libgen: 'devicon-libgen-plain',
  'z-library': 'devicon-zlibrary-plain',
  'project gutenberg': 'devicon-projectgutenberg-plain',
  'open library': 'devicon-openlibrary-plain',
  'internet archive': 'devicon-internetarchive-plain',
  wikipedia: 'devicon-wikipedia-plain',
  wikidata: 'devicon-wikidata-plain',
  wikispecies: 'devicon-wikispecies-plain',
  wikimedia: 'devicon-wikimedia-plain',
  wikibooks: 'devicon-wikibooks-plain',
  wikiversity: 'devicon-wikiversity-plain',
  wikinews: 'devicon-wikinews-plain',
  wikiquote: 'devicon-wikiquote-plain',
  wikisource: 'devicon-wikisource-plain',
  wikivoyage: 'devicon-wikivoyage-plain',
  wiktionary: 'devicon-wiktionary-plain',

  // Additional Development Tools
  'visual studio': 'devicon-visualstudio-plain',
  'visual studio code': 'devicon-vscode-plain',
  jetbrains: 'devicon-jetbrains-plain',
  'intellij idea': 'devicon-intellij-plain',
  rider: 'devicon-rider-plain',
  clion: 'devicon-clion-plain',
  datagrip: 'devicon-datagrip-plain',
  goland: 'devicon-goland-plain',
  rubymine: 'devicon-rubymine-plain',
  appcode: 'devicon-appcode-plain',
  'android studio': 'devicon-androidstudio-plain',
  xcode: 'devicon-xcode-plain',
  brackets: 'devicon-brackets-plain',
  eclipse: 'devicon-eclipse-plain',
  netbeans: 'devicon-netbeans-plain',
  emacs: 'devicon-emacs-plain',
  nano: 'devicon-nano-plain',
  terraform: 'devicon-terraform-plain',
  ansible: 'devicon-ansible-plain',
  jenkins: 'devicon-jenkins-plain',
  travis: 'devicon-travis-plain',
  circleci: 'devicon-circleci-plain',
  'github actions': 'devicon-githubactions-plain',
  'gitlab ci': 'devicon-gitlabci-plain',
  'bitbucket pipelines': 'devicon-bitbucketpipelines-plain',
  vercel: 'devicon-vercel-plain',
  netlify: 'devicon-netlify-plain',
  cloudflare: 'devicon-cloudflare-plain',
  fastly: 'devicon-fastly-plain',
  akamai: 'devicon-akamai-plain',
  iis: 'devicon-iis-plain',
  jetty: 'devicon-jetty-plain',
  wildfly: 'devicon-wildfly-plain',
  glassfish: 'devicon-glassfish-plain',
  weblogic: 'devicon-weblogic-plain',
  websphere: 'devicon-websphere-plain',
  jboss: 'devicon-jboss-plain',
  memcached: 'devicon-memcached-plain',
  rabbitmq: 'devicon-rabbitmq-plain',
  kafka: 'devicon-kafka-plain',
  solr: 'devicon-solr-plain',
  splunk: 'devicon-splunk-plain',
  grafana: 'devicon-grafana-plain',
  prometheus: 'devicon-prometheus-plain',
  logstash: 'devicon-logstash-plain',
  filebeat: 'devicon-filebeat-plain',
  metricbeat: 'devicon-metricbeat-plain',
  packetbeat: 'devicon-packetbeat-plain',
  heartbeat: 'devicon-heartbeat-plain',
  auditbeat: 'devicon-auditbeat-plain',
  functionbeat: 'devicon-functionbeat-plain',
  journalbeat: 'devicon-journalbeat-plain',
  winlogbeat: 'devicon-winlogbeat-plain',
  communitybeat: 'devicon-communitybeat-plain',
  apm: 'devicon-apm-plain',
  uptime: 'devicon-uptime-plain',
  synthetics: 'devicon-synthetics-plain',
  rum: 'devicon-rum-plain',
  security: 'devicon-security-plain',
  ml: 'devicon-ml-plain',
  maps: 'devicon-maps-plain',
  logs: 'devicon-logs-plain',
  metrics: 'devicon-metrics-plain',
  traces: 'devicon-traces-plain',
  profiling: 'devicon-profiling-plain',
  infrastructure: 'devicon-infrastructure-plain',
};
