interface objDefine {
  [key: string]: string;
}

export const moreDeviconClasses: objDefine = {
  // Additional Language Variations and Combinations
  'javascript-modern': 'devicon-javascript-plain',
  'javascript-es6': 'devicon-javascript-plain',
  'javascript-2023': 'devicon-javascript-plain',
  'typescript-latest': 'devicon-typescript-plain',
  'typescript-ts': 'devicon-typescript-plain',
  'typescript-4': 'devicon-typescript-plain',
  'python-3': 'devicon-python-plain',
  'python-latest': 'devicon-python-plain',
  'python-data': 'devicon-python-plain',
  'java-17': 'devicon-java-plain',
  'java-spring': 'devicon-java-plain',
  'java-enterprise': 'devicon-java-plain',
  'cpp-17': 'devicon-cplusplus-plain',
  'cpp-modern': 'devicon-cplusplus-plain',
  'cpp-latest': 'devicon-cplusplus-plain',

  // Framework Variations with Versions
  'react-18': 'devicon-react-original',
  'react-latest': 'devicon-react-original',
  'react-hooks': 'devicon-react-original',
  'vue-3': 'devicon-vuejs-plain',
  'vue-next': 'devicon-vuejs-plain',
  'vue-latest': 'devicon-vuejs-plain',
  'angular-latest': 'devicon-angularjs-plain',
  'angular-15': 'devicon-angularjs-plain',
  'angular-modern': 'devicon-angularjs-plain',
  'nextjs-13': 'devicon-nextjs-plain',
  'nextjs-latest': 'devicon-nextjs-plain',
  'nextjs-app': 'devicon-nextjs-plain',

  // Database Variations with Versions
  'mongodb-latest': 'devicon-mongodb-plain',
  'mongodb-atlas': 'devicon-mongodb-plain',
  'mongodb-cloud': 'devicon-mongodb-plain',
  'mysql-8': 'devicon-mysql-plain',
  'mysql-latest': 'devicon-mysql-plain',
  'mysql-modern': 'devicon-mysql-plain',
  'postgresql-15': 'devicon-postgresql-plain',
  'postgresql-latest': 'devicon-postgresql-plain',
  'postgresql-cloud': 'devicon-postgresql-plain',

  // Cloud and DevOps Variations
  'aws-lambda': 'devicon-amazonwebservices-original',
  'aws-s3': 'devicon-amazonwebservices-original',
  'aws-ec2': 'devicon-amazonwebservices-original',
  'aws-rds': 'devicon-amazonwebservices-original',
  'aws-cloudfront': 'devicon-amazonwebservices-original',
  'aws-route53': 'devicon-amazonwebservices-original',
  'aws-dynamodb': 'devicon-amazonwebservices-original',
  'aws-sqs': 'devicon-amazonwebservices-original',
  'aws-sns': 'devicon-amazonwebservices-original',
  'aws-apigateway': 'devicon-amazonwebservices-original',
  'azure-functions': 'devicon-azure-plain',
  'azure-storage': 'devicon-azure-plain',
  'azure-sqldb': 'devicon-azure-plain',
  'azure-cosmos': 'devicon-azure-plain',
  'azure-devops': 'devicon-azure-plain',
  'azure-aks': 'devicon-azure-plain',
  'gcp-bigquery': 'devicon-googlecloud-plain',
  'gcp-datastore': 'devicon-googlecloud-plain',
  'gcp-functions': 'devicon-googlecloud-plain',
  'gcp-compute': 'devicon-googlecloud-plain',
  'gcp-kubernetes': 'devicon-googlecloud-plain',

  // Mobile Development Variations
  'react-native-latest': 'devicon-react-original',
  'react-native-android': 'devicon-react-original',
  'react-native-ios': 'devicon-react-original',
  'flutter-latest': 'devicon-flutter-plain',
  'flutter-web': 'devicon-flutter-plain',
  'flutter-material': 'devicon-flutter-plain',
  'swift-ios': 'devicon-swift-plain',
  'swift-latest': 'devicon-swift-plain',
  'swift-ui': 'devicon-swift-plain',
  'kotlin-android': 'devicon-kotlin-plain',
  'kotlin-latest': 'devicon-kotlin-plain',
  'kotlin-multiplatform': 'devicon-kotlin-plain',

  // CSS Framework Variations
  'tailwind-latest': 'devicon-tailwindcss-plain',
  'tailwind-ui': 'devicon-tailwindcss-plain',
  'tailwind-jit': 'devicon-tailwindcss-plain',
  'bootstrap-5': 'devicon-bootstrap-plain',
  'bootstrap-latest': 'devicon-bootstrap-plain',
  'bootstrap-responsive': 'devicon-bootstrap-plain',
  'materialui-latest': 'devicon-materialui-plain',
  'materialui-v5': 'devicon-materialui-plain',
  'materialui-react': 'devicon-materialui-plain',

  // Testing Framework Variations
  'jest-react': 'devicon-jest-plain',
  'jest-typescript': 'devicon-jest-plain',
  'jest-latest': 'devicon-jest-plain',
  'cypress-e2e': 'devicon-cypress-plain',
  'cypress-component': 'devicon-cypress-plain',
  'cypress-latest': 'devicon-cypress-plain',
  'selenium-java': 'devicon-selenium-original',
  'selenium-python': 'devicon-selenium-original',
  'selenium-latest': 'devicon-selenium-original',

  // Build Tool Variations
  'webpack-5': 'devicon-webpack-plain',
  'webpack-latest': 'devicon-webpack-plain',
  'webpack-module': 'devicon-webpack-plain',
  'vite-latest': 'devicon-vite-plain',
  'vite-react': 'devicon-vite-plain',
  'vite-vue': 'devicon-vite-plain',
  'babel-latest': 'devicon-babel-plain',
  'babel-core': 'devicon-babel-plain',
  'babel-preset': 'devicon-babel-plain',

  // IDE Variations
  'vscode-latest': 'devicon-vscode-plain',
  'vscode-insiders': 'devicon-vscode-plain',
  'vscode-extensions': 'devicon-vscode-plain',
  'intellij-latest': 'devicon-intellij-plain',
  'intellij-ultimate': 'devicon-intellij-plain',
  'intellij-community': 'devicon-intellij-plain',
  'webstorm-latest': 'devicon-webstorm-plain',
  'webstorm-202x': 'devicon-webstorm-plain',
  'pycharm-latest': 'devicon-pycharm-plain',
  'pycharm-professional': 'devicon-pycharm-plain',
  'pycharm-community': 'devicon-pycharm-plain',

  // Operating System Variations
  'linux-debian': 'devicon-linux-plain',
  'linux-ubuntu': 'devicon-linux-plain',
  'linux-fedora': 'devicon-linux-plain',
  'linux-redhat': 'devicon-linux-plain',
  'linux-arch': 'devicon-linux-plain',
  'linux-mint': 'devicon-linux-plain',
  'linux-centos': 'devicon-linux-plain',
  'windows-10': 'devicon-windows8-original',
  'windows-11': 'devicon-windows8-original',
  'windows-server': 'devicon-windows8-original',
  'macos-latest': 'devicon-apple-original',
  'macos-ventura': 'devicon-apple-original',
  'macos-monterey': 'devicon-apple-original',

  // Additional Language Combinations by Domain
  'javascript-frontend': 'devicon-javascript-plain',
  'javascript-backend': 'devicon-javascript-plain',
  'javascript-fullstack': 'devicon-javascript-plain',
  'typescript-frontend': 'devicon-typescript-plain',
  'typescript-backend': 'devicon-typescript-plain',
  'typescript-fullstack': 'devicon-typescript-plain',
  'python-web': 'devicon-python-plain',
  'python-ai': 'devicon-python-plain',
  'python-ml': 'devicon-python-plain',
  'python-data-science': 'devicon-python-plain',
  'python-scientific': 'devicon-python-plain',
  'python-scripting': 'devicon-python-plain',
  'python-automation': 'devicon-python-plain',
  'java-backend': 'devicon-java-plain',
  'java-android': 'devicon-java-plain',
  'java-server': 'devicon-java-plain',
  'cpp-systems': 'devicon-cplusplus-plain',
  'cpp-game': 'devicon-cplusplus-plain',
  'cpp-embedded': 'devicon-cplusplus-plain',
  'ruby-web': 'devicon-ruby-plain',
  'ruby-rails': 'devicon-ruby-plain',
  'php-web': 'devicon-php-plain',
  'php-server': 'devicon-php-plain',

  // Framework Domain-Specific Variants
  'react-enterprise': 'devicon-react-original',
  'react-ecommerce': 'devicon-react-original',
  'react-spa': 'devicon-react-original',
  'react-dashboard': 'devicon-react-original',
  'vue-enterprise': 'devicon-vuejs-plain',
  'vue-ecommerce': 'devicon-vuejs-plain',
  'vue-spa': 'devicon-vuejs-plain',
  'angular-enterprise': 'devicon-angularjs-plain',
  'angular-dashboard': 'devicon-angularjs-plain',
  'nextjs-ecommerce': 'devicon-nextjs-plain',
  'nextjs-blog': 'devicon-nextjs-plain',
  'nextjs-enterprise': 'devicon-nextjs-plain',
  'django-web': 'devicon-django-plain',
  'django-api': 'devicon-django-plain',
  'django-cms': 'devicon-django-plain',
  'spring-boot': 'devicon-spring-plain',
  'spring-cloud': 'devicon-spring-plain',
  'spring-security': 'devicon-spring-plain',
  'laravel-web': 'devicon-laravel-plain',
  'laravel-api': 'devicon-laravel-plain',
  'laravel-ecommerce': 'devicon-laravel-plain',

  // Database Use Case Variants
  'mongodb-nosql': 'devicon-mongodb-plain',
  'mongodb-document': 'devicon-mongodb-plain',
  'mongodb-realtime': 'devicon-mongodb-plain',
  'mysql-relational': 'devicon-mysql-plain',
  'mysql-ecommerce': 'devicon-mysql-plain',
  'mysql-cms': 'devicon-mysql-plain',
  'postgresql-relational': 'devicon-postgresql-plain',
  'postgresql-enterprise': 'devicon-postgresql-plain',
  'postgresql-geospatial': 'devicon-postgresql-plain',
  'redis-cache': 'devicon-redis-plain',
  'redis-session': 'devicon-redis-plain',
  'redis-queue': 'devicon-redis-plain',

  // Cloud Provider Service Specific Variants
  'aws-full': 'devicon-amazonwebservices-original',
  'aws-serverless': 'devicon-amazonwebservices-original',
  'aws-containers': 'devicon-amazonwebservices-original',
  'azure-full': 'devicon-azure-plain',
  'azure-serverless': 'devicon-azure-plain',
  'azure-containers': 'devicon-azure-plain',
  'gcp-full': 'devicon-googlecloud-plain',
  'gcp-serverless': 'devicon-googlecloud-plain',
  'gcp-containers': 'devicon-googlecloud-plain',

  // Domain-Specific Technologies
  'ai-development': 'devicon-python-plain',
  'ml-development': 'devicon-python-plain',
  'data-science': 'devicon-python-plain',
  'web-development': 'devicon-html5-plain',
  'mobile-development': 'devicon-react-original',
  'game-development': 'devicon-unity-original',
  'cloud-development': 'devicon-amazonwebservices-original',
  'devops-engineer': 'devicon-docker-plain',
  'database-engineer': 'devicon-postgresql-plain',
  'frontend-developer': 'devicon-react-original',
  'backend-developer': 'devicon-nodejs-plain',
  'fullstack-developer': 'devicon-javascript-plain',

  // Special Technology Combinations
  'mern-stack': 'devicon-mongodb-plain',
  'mean-stack': 'devicon-mongodb-plain',
  'lamp-stack': 'devicon-linux-plain',
  'lemp-stack': 'devicon-nginx-original',
  'jamstack-dev': 'devicon-javascript-plain',
  'serverless-dev': 'devicon-amazonwebservices-original',
  'containerized-dev': 'devicon-docker-plain',
  'microservices-arch': 'devicon-kubernetes-plain',
  'monolith-arch': 'devicon-nodejs-plain',

  // Technology Combinations by Project Type
  'ecommerce-tech': 'devicon-react-original',
  'blog-tech': 'devicon-nextjs-plain',
  'cms-tech': 'devicon-wordpress-plain',
  'saas-tech': 'devicon-nodejs-plain',
  'enterprise-tech': 'devicon-java-plain',
  'startup-tech': 'devicon-javascript-plain',
  'social-media-tech': 'devicon-react-original',
  'fintech-tech': 'devicon-java-plain',
  'edtech-tech': 'devicon-python-plain',
  'healthtech-tech': 'devicon-react-original',

  // Additional Special Classes
  'tech-2023': 'devicon-javascript-plain',
  'tech-frontend': 'devicon-html5-plain',
  'tech-backend': 'devicon-nodejs-plain',
  'tech-fullstack': 'devicon-javascript-plain',
  'tech-mobile': 'devicon-react-original',
  'tech-web': 'devicon-html5-plain',
  'tech-ai': 'devicon-python-plain',
  'tech-ml': 'devicon-python-plain',
  'tech-data': 'devicon-python-plain',
  'tech-cloud': 'devicon-amazonwebservices-original',
  'tech-devops': 'devicon-docker-plain',
  'tech-database': 'devicon-postgresql-plain',

  // Specialty Area Combinations
  'cybersecurity-tech': 'devicon-linux-plain',
  'networking-tech': 'devicon-nginx-original',
  'embedded-tech': 'devicon-cplusplus-plain',
  'iot-tech': 'devicon-raspberrypi-plain',
  'ar-vr-tech': 'devicon-unity-original',
  'blockchain-tech': 'devicon-javascript-plain',
  'quantum-tech': 'devicon-python-plain',

  // Google
  google: 'devicon-google-plain',
  'google-cloud': 'devicon-googlecloud-plain',
  'google-workspace': 'devicon-googleworkspace-plain',
  'google-analytics': 'devicon-googleanalytics-plain',
  'google-ads': 'devicon-googleads-plain',
  'google-cloud-platform': 'devicon-googlecloud-plain',
};
