# Azure Static Web Apps Deploy Workflow

name: Azure Static Web Apps Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout code from repository
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install dependencies with --legacy-peer-deps
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # Build the application
      - name: Build Application
        run: npm run build

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          api_location: "api"
